- name: Install the Nginx package
  apt:
    name: nginx
    state: present
  become: yes

- name: Remove default nginx conf
  file:
   path: /etc/nginx/sites-enabled/default
   state: absent
  become: yes

- name: Create sites-enabled configuration directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
  become: yes
   
- name: Create sites-available configuration directory
  file:
    path: /etc/nginx/sites-available
    state: directory
  become: yes

- name: copy nginx configuration file
  template:
    src: templates/nginx_frontend.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: copy sample virtualhost configuration
  template:
    src: templates/vhost_frontend.j2
    dest: /etc/nginx/sites-available/{{ nginx_server_name }}.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Symlink nginx server conf
  file:
    src: /etc/nginx/sites-available/{{ nginx_server_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_server_name }}.conf
    state: link
  become: yes

- name: copy sample custom blacklist nginx configuration
  template:
    src: files/blockbot.conf
    dest: /etc/nginx/custom/
    owner: root
    group: root
    mode: 0644
  become: yes

- name: reload nginx
  service:
    name: nginx
    state: restarted
  become: yes
